apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: semaphore
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: semaphore
  dataFrom:
    - extract:
        key: prod-semaphore
