apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "thelman1991@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod-http
    solvers:
    - selector:
        dnsZones:
          - "toolchain.mx"
      dns01:
        route53:
          region: us-east-1